// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/weige/github/ui/node_modules/.pnpm/dumi@2.2.4_@babel+core@7.22.9_@types+node@20.4.5_eslint@8.46.0_jest@29.6.2_postcss@8.4.27_pre_okqrp62plagpwnt3ldsv5le5wm/node_modules/dumi/theme-default/layouts/DocLayout/index.js';
